package machines;

/**
 *
 * @author adji
 */
public enum MachineStateType {

    WAITING,
    ERROR,
    BILL_DEPOSIT_START,
    BILL_DEPOSIT_CONTINUE,
    BILL_DEPOSIT_READY_TO_STORE,
    BILL_DEPOSIT_READY_TO_STORE_ESCROW_FULL,
    BILL_DEPOSIT_STORING,
    BILL_DEPOSIT_STORING_ESCROW_FULL,
    BILL_DEPOSIT_WITHDRAW,
    ENVELOPE_DEPOSIT_START,
    ENVELOPE_DEPOSIT_READY_TO_STORE,
    ENVELOPE_DEPOSIT_STORING,
    COUNTING_START,
    FILTERING_START,
    BAG_REMOVED,
    JAM,
    PRINTER_NOT_READY,
    REMOVE_REJECTED_BILLS,
    CANCELING,
    CONFIRM_WAIT,
    CONFIRMED,
    WAITING_FOR_CLOSED_GATE,
    WAITING_FOR_OPEN_GATE,
}
