package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LgAclRule generated by hbm2java
 */
@Entity
@Table(name="lg_acl_rule"
    ,schema="public"
)
public class LgAclRule  implements java.io.Serializable {


     private int aclId;
     private LgRole lgRole;
     private LgResource lgResource;
     private int priority;
     private String permission;
     private String operation;

    public LgAclRule() {
    }

    public LgAclRule(int aclId, LgRole lgRole, LgResource lgResource, int priority, String permission, String operation) {
       this.aclId = aclId;
       this.lgRole = lgRole;
       this.lgResource = lgResource;
       this.priority = priority;
       this.permission = permission;
       this.operation = operation;
    }
   
     @Id 
    
    @Column(name="acl_id", unique=true, nullable=false)
    public int getAclId() {
        return this.aclId;
    }
    
    public void setAclId(int aclId) {
        this.aclId = aclId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public LgRole getLgRole() {
        return this.lgRole;
    }
    
    public void setLgRole(LgRole lgRole) {
        this.lgRole = lgRole;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_id", nullable=false)
    public LgResource getLgResource() {
        return this.lgResource;
    }
    
    public void setLgResource(LgResource lgResource) {
        this.lgResource = lgResource;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    @Column(name="permission", nullable=false, length=8)
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    
    @Column(name="operation", nullable=false, length=64)
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }




}


