package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgBag generated by hbm2java
 */
@Entity
@Table(name="lg_bag"
    ,schema="public"
)
public class LgBag  implements java.io.Serializable {


     private int bagId;
     private String bagCode;
     private Date creationDate;
     private Date withdrawDate;
     private Set<LgDeposit> lgDeposits = new HashSet<LgDeposit>(0);

    public LgBag() {
    }

	
    public LgBag(int bagId, String bagCode, Date creationDate) {
        this.bagId = bagId;
        this.bagCode = bagCode;
        this.creationDate = creationDate;
    }
    public LgBag(int bagId, String bagCode, Date creationDate, Date withdrawDate, Set<LgDeposit> lgDeposits) {
       this.bagId = bagId;
       this.bagCode = bagCode;
       this.creationDate = creationDate;
       this.withdrawDate = withdrawDate;
       this.lgDeposits = lgDeposits;
    }
   
     @Id 
    
    @Column(name="bag_id", unique=true, nullable=false)
    public int getBagId() {
        return this.bagId;
    }
    
    public void setBagId(int bagId) {
        this.bagId = bagId;
    }
    
    @Column(name="bag_code", nullable=false, length=128)
    public String getBagCode() {
        return this.bagCode;
    }
    
    public void setBagCode(String bagCode) {
        this.bagCode = bagCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="withdraw_date", length=13)
    public Date getWithdrawDate() {
        return this.withdrawDate;
    }
    
    public void setWithdrawDate(Date withdrawDate) {
        this.withdrawDate = withdrawDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgBag")
    public Set<LgDeposit> getLgDeposits() {
        return this.lgDeposits;
    }
    
    public void setLgDeposits(Set<LgDeposit> lgDeposits) {
        this.lgDeposits = lgDeposits;
    }




}


