package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgBatch generated by hbm2java
 */
@Entity
@Table(name="lg_batch"
    ,schema="public"
)
public class LgBatch  implements java.io.Serializable {


     private int batchId;
     private Date creationDate;
     private Set<LgBill> lgBills = new HashSet<LgBill>(0);

    public LgBatch() {
    }

	
    public LgBatch(int batchId, Date creationDate) {
        this.batchId = batchId;
        this.creationDate = creationDate;
    }
    public LgBatch(int batchId, Date creationDate, Set<LgBill> lgBills) {
       this.batchId = batchId;
       this.creationDate = creationDate;
       this.lgBills = lgBills;
    }
   
     @Id 
    
    @Column(name="batch_id", unique=true, nullable=false)
    public int getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(int batchId) {
        this.batchId = batchId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgBatch")
    public Set<LgBill> getLgBills() {
        return this.lgBills;
    }
    
    public void setLgBills(Set<LgBill> lgBills) {
        this.lgBills = lgBills;
    }




}


