package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LgBill generated by hbm2java
 */
@Entity
@Table(name="lg_bill"
    ,schema="public"
)
public class LgBill  implements java.io.Serializable {


     private int billId;
     private LgDeposit lgDeposit;
     private LgBatch lgBatch;
     private int quantity;
     private int amount;
     private int unitLob;

    public LgBill() {
    }

    public LgBill(int billId, LgDeposit lgDeposit, LgBatch lgBatch, int quantity, int amount, int unitLob) {
       this.billId = billId;
       this.lgDeposit = lgDeposit;
       this.lgBatch = lgBatch;
       this.quantity = quantity;
       this.amount = amount;
       this.unitLob = unitLob;
    }
   
     @Id 
    
    @Column(name="bill_id", unique=true, nullable=false)
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deposit_id", nullable=false)
    public LgDeposit getLgDeposit() {
        return this.lgDeposit;
    }
    
    public void setLgDeposit(LgDeposit lgDeposit) {
        this.lgDeposit = lgDeposit;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="batch_id", nullable=false)
    public LgBatch getLgBatch() {
        return this.lgBatch;
    }
    
    public void setLgBatch(LgBatch lgBatch) {
        this.lgBatch = lgBatch;
    }
    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    
    @Column(name="unit_lob", nullable=false)
    public int getUnitLob() {
        return this.unitLob;
    }
    
    public void setUnitLob(int unitLob) {
        this.unitLob = unitLob;
    }




}


