package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgDeposit generated by hbm2java
 */
@Entity
@Table(name="lg_deposit"
    ,schema="public"
)
public class LgDeposit  implements java.io.Serializable {


     private int depositId;
     private LgBag lgBag;
     private Date creationDate;
     private Date startDate;
     private Date finishDate;
     private String userCode;
     private Integer userCodeLov;
     private Set<LgEnvelope> lgEnvelopes = new HashSet<LgEnvelope>(0);
     private Set<LgBill> lgBills = new HashSet<LgBill>(0);
     private Set<LgExternalAppLog> lgExternalAppLogs = new HashSet<LgExternalAppLog>(0);

    public LgDeposit() {
    }

	
    public LgDeposit(int depositId, LgBag lgBag, Date creationDate) {
        this.depositId = depositId;
        this.lgBag = lgBag;
        this.creationDate = creationDate;
    }
    public LgDeposit(int depositId, LgBag lgBag, Date creationDate, Date startDate, Date finishDate, String userCode, Integer userCodeLov, Set<LgEnvelope> lgEnvelopes, Set<LgBill> lgBills, Set<LgExternalAppLog> lgExternalAppLogs) {
       this.depositId = depositId;
       this.lgBag = lgBag;
       this.creationDate = creationDate;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.userCode = userCode;
       this.userCodeLov = userCodeLov;
       this.lgEnvelopes = lgEnvelopes;
       this.lgBills = lgBills;
       this.lgExternalAppLogs = lgExternalAppLogs;
    }
   
     @Id 
    
    @Column(name="deposit_id", unique=true, nullable=false)
    public int getDepositId() {
        return this.depositId;
    }
    
    public void setDepositId(int depositId) {
        this.depositId = depositId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bag_id", nullable=false)
    public LgBag getLgBag() {
        return this.lgBag;
    }
    
    public void setLgBag(LgBag lgBag) {
        this.lgBag = lgBag;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=13)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="finish_date", length=13)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    
    @Column(name="user_code", length=128)
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    
    @Column(name="user_code_lov")
    public Integer getUserCodeLov() {
        return this.userCodeLov;
    }
    
    public void setUserCodeLov(Integer userCodeLov) {
        this.userCodeLov = userCodeLov;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgDeposit")
    public Set<LgEnvelope> getLgEnvelopes() {
        return this.lgEnvelopes;
    }
    
    public void setLgEnvelopes(Set<LgEnvelope> lgEnvelopes) {
        this.lgEnvelopes = lgEnvelopes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgDeposit")
    public Set<LgBill> getLgBills() {
        return this.lgBills;
    }
    
    public void setLgBills(Set<LgBill> lgBills) {
        this.lgBills = lgBills;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgDeposit")
    public Set<LgExternalAppLog> getLgExternalAppLogs() {
        return this.lgExternalAppLogs;
    }
    
    public void setLgExternalAppLogs(Set<LgExternalAppLog> lgExternalAppLogs) {
        this.lgExternalAppLogs = lgExternalAppLogs;
    }




}


