package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LgEnvelope generated by hbm2java
 */
@Entity
@Table(name="lg_envelope"
    ,schema="public"
)
public class LgEnvelope  implements java.io.Serializable {


     private int envelopeId;
     private LgDeposit lgDeposit;
     private String userCode;
     private int amount;
     private int unitLov;

    public LgEnvelope() {
    }

    public LgEnvelope(int envelopeId, LgDeposit lgDeposit, String userCode, int amount, int unitLov) {
       this.envelopeId = envelopeId;
       this.lgDeposit = lgDeposit;
       this.userCode = userCode;
       this.amount = amount;
       this.unitLov = unitLov;
    }
   
     @Id 
    
    @Column(name="envelope_id", unique=true, nullable=false)
    public int getEnvelopeId() {
        return this.envelopeId;
    }
    
    public void setEnvelopeId(int envelopeId) {
        this.envelopeId = envelopeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deposit_id", nullable=false)
    public LgDeposit getLgDeposit() {
        return this.lgDeposit;
    }
    
    public void setLgDeposit(LgDeposit lgDeposit) {
        this.lgDeposit = lgDeposit;
    }
    
    @Column(name="user_code", nullable=false, length=128)
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    
    @Column(name="unit_lov", nullable=false)
    public int getUnitLov() {
        return this.unitLov;
    }
    
    public void setUnitLov(int unitLov) {
        this.unitLov = unitLov;
    }




}


