package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgExternalAppLog generated by hbm2java
 */
@Entity
@Table(name="lg_external_app_log"
    ,schema="public"
)
public class LgExternalAppLog  implements java.io.Serializable {


     private int logId;
     private LgExternalApp lgExternalApp;
     private LgDeposit lgDeposit;
     private Date creationDate;
     private String resultCode;

    public LgExternalAppLog() {
    }

    public LgExternalAppLog(int logId, LgExternalApp lgExternalApp, LgDeposit lgDeposit, Date creationDate, String resultCode) {
       this.logId = logId;
       this.lgExternalApp = lgExternalApp;
       this.lgDeposit = lgDeposit;
       this.creationDate = creationDate;
       this.resultCode = resultCode;
    }
   
     @Id 
    
    @Column(name="log_id", unique=true, nullable=false)
    public int getLogId() {
        return this.logId;
    }
    
    public void setLogId(int logId) {
        this.logId = logId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="external_app_id", nullable=false)
    public LgExternalApp getLgExternalApp() {
        return this.lgExternalApp;
    }
    
    public void setLgExternalApp(LgExternalApp lgExternalApp) {
        this.lgExternalApp = lgExternalApp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deposit_id", nullable=false)
    public LgDeposit getLgDeposit() {
        return this.lgDeposit;
    }
    
    public void setLgDeposit(LgDeposit lgDeposit) {
        this.lgDeposit = lgDeposit;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=13)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="result_code", nullable=false, length=32)
    public String getResultCode() {
        return this.resultCode;
    }
    
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }




}


