package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LgExternalApp generated by hbm2java
 */
@Entity
@Table(name="lg_external_app"
    ,schema="public"
)
public class LgExternalApp  implements java.io.Serializable {


     private int externalAppId;
     private String name;
     private Set<LgUser> lgUsers = new HashSet<LgUser>(0);
     private Set<LgExternalAppLog> lgExternalAppLogs = new HashSet<LgExternalAppLog>(0);

    public LgExternalApp() {
    }

	
    public LgExternalApp(int externalAppId, String name) {
        this.externalAppId = externalAppId;
        this.name = name;
    }
    public LgExternalApp(int externalAppId, String name, Set<LgUser> lgUsers, Set<LgExternalAppLog> lgExternalAppLogs) {
       this.externalAppId = externalAppId;
       this.name = name;
       this.lgUsers = lgUsers;
       this.lgExternalAppLogs = lgExternalAppLogs;
    }
   
     @Id 
    
    @Column(name="external_app_id", unique=true, nullable=false)
    public int getExternalAppId() {
        return this.externalAppId;
    }
    
    public void setExternalAppId(int externalAppId) {
        this.externalAppId = externalAppId;
    }
    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgExternalApp")
    public Set<LgUser> getLgUsers() {
        return this.lgUsers;
    }
    
    public void setLgUsers(Set<LgUser> lgUsers) {
        this.lgUsers = lgUsers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgExternalApp")
    public Set<LgExternalAppLog> getLgExternalAppLogs() {
        return this.lgExternalAppLogs;
    }
    
    public void setLgExternalAppLogs(Set<LgExternalAppLog> lgExternalAppLogs) {
        this.lgExternalAppLogs = lgExternalAppLogs;
    }




}


