package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LgLovId generated by hbm2java
 */
@Embeddable
public class LgLovId  implements java.io.Serializable {


     private String type;
     private int numericId;
     private String textId;

    public LgLovId() {
    }

    public LgLovId(String type, int numericId, String textId) {
       this.type = type;
       this.numericId = numericId;
       this.textId = textId;
    }
   

    @Column(name="type", nullable=false, length=32)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Column(name="numeric_id", nullable=false)
    public int getNumericId() {
        return this.numericId;
    }
    
    public void setNumericId(int numericId) {
        this.numericId = numericId;
    }

    @Column(name="text_id", nullable=false, length=32)
    public String getTextId() {
        return this.textId;
    }
    
    public void setTextId(String textId) {
        this.textId = textId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LgLovId) ) return false;
		 LgLovId castOther = ( LgLovId ) other; 
         
		 return ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && (this.getNumericId()==castOther.getNumericId())
 && ( (this.getTextId()==castOther.getTextId()) || ( this.getTextId()!=null && castOther.getTextId()!=null && this.getTextId().equals(castOther.getTextId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + this.getNumericId();
         result = 37 * result + ( getTextId() == null ? 0 : this.getTextId().hashCode() );
         return result;
   }   


}


