package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgLov generated by hbm2java
 */
@Entity
@Table(name="lg_lov"
    ,schema="public"
)
public class LgLov  implements java.io.Serializable {


     private LgLovId id;
     private String description;
     private Date endDate;

    public LgLov() {
    }

    public LgLov(LgLovId id, String description, Date endDate) {
       this.id = id;
       this.description = description;
       this.endDate = endDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="type", column=@Column(name="type", nullable=false, length=32) ), 
        @AttributeOverride(name="numericId", column=@Column(name="numeric_id", nullable=false) ), 
        @AttributeOverride(name="textId", column=@Column(name="text_id", nullable=false, length=32) ) } )
    public LgLovId getId() {
        return this.id;
    }
    
    public void setId(LgLovId id) {
        this.id = id;
    }
    
    @Column(name="description", nullable=false, length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=13)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


