package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LgResource generated by hbm2java
 */
@Entity
@Table(name="lg_resource"
    ,schema="public"
)
public class LgResource  implements java.io.Serializable {


     private int resourceId;
     private String name;
     private Set<LgAclRule> lgAclRules = new HashSet<LgAclRule>(0);

    public LgResource() {
    }

	
    public LgResource(int resourceId, String name) {
        this.resourceId = resourceId;
        this.name = name;
    }
    public LgResource(int resourceId, String name, Set<LgAclRule> lgAclRules) {
       this.resourceId = resourceId;
       this.name = name;
       this.lgAclRules = lgAclRules;
    }
   
     @Id 
    
    @Column(name="resource_id", unique=true, nullable=false)
    public int getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(int resourceId) {
        this.resourceId = resourceId;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgResource")
    public Set<LgAclRule> getLgAclRules() {
        return this.lgAclRules;
    }
    
    public void setLgAclRules(Set<LgAclRule> lgAclRules) {
        this.lgAclRules = lgAclRules;
    }




}


