package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LgRole generated by hbm2java
 */
@Entity
@Table(name="lg_role"
    ,schema="public"
)
public class LgRole  implements java.io.Serializable {


     private int roleId;
     private LgRole lgRole;
     private String name;
     private Set<LgAclRule> lgAclRules = new HashSet<LgAclRule>(0);
     private Set<LgRole> lgRoles = new HashSet<LgRole>(0);
     private Set<LgUser> lgUsers = new HashSet<LgUser>(0);

    public LgRole() {
    }

	
    public LgRole(int roleId, String name) {
        this.roleId = roleId;
        this.name = name;
    }
    public LgRole(int roleId, LgRole lgRole, String name, Set<LgAclRule> lgAclRules, Set<LgRole> lgRoles, Set<LgUser> lgUsers) {
       this.roleId = roleId;
       this.lgRole = lgRole;
       this.name = name;
       this.lgAclRules = lgAclRules;
       this.lgRoles = lgRoles;
       this.lgUsers = lgUsers;
    }
   
     @Id 
    
    @Column(name="role_id", unique=true, nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_role_id")
    public LgRole getLgRole() {
        return this.lgRole;
    }
    
    public void setLgRole(LgRole lgRole) {
        this.lgRole = lgRole;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgRole")
    public Set<LgAclRule> getLgAclRules() {
        return this.lgAclRules;
    }
    
    public void setLgAclRules(Set<LgAclRule> lgAclRules) {
        this.lgAclRules = lgAclRules;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgRole")
    public Set<LgRole> getLgRoles() {
        return this.lgRoles;
    }
    
    public void setLgRoles(Set<LgRole> lgRoles) {
        this.lgRoles = lgRoles;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lgRoles")
    public Set<LgUser> getLgUsers() {
        return this.lgUsers;
    }
    
    public void setLgUsers(Set<LgUser> lgUsers) {
        this.lgUsers = lgUsers;
    }




}


