package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LgSystemProperty generated by hbm2java
 */
@Entity
@Table(name="lg_system_property"
    ,schema="public"
)
public class LgSystemProperty  implements java.io.Serializable {


     private int propertyId;
     private String name;
     private String value;

    public LgSystemProperty() {
    }

    public LgSystemProperty(int propertyId, String name, String value) {
       this.propertyId = propertyId;
       this.name = name;
       this.value = value;
    }
   
     @Id 
    
    @Column(name="property_id", unique=true, nullable=false)
    public int getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="value", nullable=false, length=128)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


