package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LgUserProperty generated by hbm2java
 */
@Entity
@Table(name="lg_user_property"
    ,schema="public"
)
public class LgUserProperty  implements java.io.Serializable {


     private LgUserPropertyId id;
     private LgUser lgUser;
     private String value;

    public LgUserProperty() {
    }

    public LgUserProperty(LgUserPropertyId id, LgUser lgUser, String value) {
       this.id = id;
       this.lgUser = lgUser;
       this.value = value;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="property", column=@Column(name="property", nullable=false, length=64) ) } )
    public LgUserPropertyId getId() {
        return this.id;
    }
    
    public void setId(LgUserPropertyId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public LgUser getLgUser() {
        return this.lgUser;
    }
    
    public void setLgUser(LgUser lgUser) {
        this.lgUser = lgUser;
    }
    
    @Column(name="value", nullable=false, length=128)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


