package models;
// Generated Jun 26, 2012 9:57:59 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LgUserPropertyId generated by hbm2java
 */
@Embeddable
public class LgUserPropertyId  implements java.io.Serializable {


     private int userId;
     private String property;

    public LgUserPropertyId() {
    }

    public LgUserPropertyId(int userId, String property) {
       this.userId = userId;
       this.property = property;
    }
   

    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name="property", nullable=false, length=64)
    public String getProperty() {
        return this.property;
    }
    
    public void setProperty(String property) {
        this.property = property;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LgUserPropertyId) ) return false;
		 LgUserPropertyId castOther = ( LgUserPropertyId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getProperty()==castOther.getProperty()) || ( this.getProperty()!=null && castOther.getProperty()!=null && this.getProperty().equals(castOther.getProperty()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getProperty() == null ? 0 : this.getProperty().hashCode() );
         return result;
   }   


}


